controller_manager:
    ros_parameters:
        update_rate: 100 # update_rate specifies how often (in Hz) the controllers should be updated.

        # The JointTrajectoryController allows you to send joint trajectory commands to a group 
        # of joints on a robot. These commands specify the desired positions for each joint.
        arm_controller:
            type: joint_trajectory_controller/JointTrajectoryController

        # An optional additional controller to control the gripper. 
        # This interface is preferred to JointTrajectoryController above.
#        gripper_controller:
#            type: joint_trajectory_controller/JointTrajectoryController
        gripper_controller:
            type: forward_command_controller/ForwardCommandController

        # Responsible for publishing the current state of the robot's joints to the /joint_states 
        # ROS 2 topic
        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster
# Define the parameters for each controller
arm_controller:
    rost_parameters:
        joints:
            - joint_1
            - joint_2
            - joint_3
        
        # The controller will expect position commands as input for each of these joints.
        command_interfaces:
            - position
    
        # Tells the controller that it should expect to receive position data as the state 
        # feedback from the hardware interface,
        state_interfaces:
            - position
        
        # If true, When set to true, the controller will not use any feedback from the system 
        # (e.g., joint positions, velocities, efforts) to compute the control commands.
        open_loop_control: true
        
        # When set to true, it allows the controller to integrate the trajectory goals it receives. 
        # This means that if the goal trajectory only specifies positions, the controller will 
        # numerically integrate the positions to compute the velocities and accelerations required 
        # to follow the trajectory.
        allow_integration_in_goal_trajectories: true

gripper_controller:
    ros_parameters:
        joints:
            - joint_4
        interface_name: position

#        command_interfaces:
#            - position
#        state_interfaces:
#            - position
#        open_loop_control: true
#        allow_integration_in_goal_trajectories: true